<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CountriesLookupSeeder extends Seeder
{
    public function run()
    {
        $greekStringConversion = new \App\Services\GreekStringConversionHelper();
        \DB::table('countries_lookup')->insert(
            array(
                array('code' => 'AC', 'name' => $greekStringConversion->grstrtoupper('Νήσος Ασενσιόν')),
                array('code' => 'AD', 'name' => $greekStringConversion->grstrtoupper('Ανδόρα')),
                array('code' => 'AE', 'name' => $greekStringConversion->grstrtoupper('Ηνωμένα Αραβικά Εμιράτα')),
                array('code' => 'AF', 'name' => $greekStringConversion->grstrtoupper('Αφγανιστάν')),
                array('code' => 'AG', 'name' => $greekStringConversion->grstrtoupper('Αντίγκουα και Μπαρμπούντα')),
                array('code' => 'AI', 'name' => $greekStringConversion->grstrtoupper('Ανγκουίλα')),
                array('code' => 'AL', 'name' => $greekStringConversion->grstrtoupper('Αλβανία')),
                array('code' => 'AM', 'name' => $greekStringConversion->grstrtoupper('Αρμενία')),
                array('code' => 'AO', 'name' => $greekStringConversion->grstrtoupper('Ανγκόλα')),
                array('code' => 'AQ', 'name' => $greekStringConversion->grstrtoupper('Ανταρκτική')),
                array('code' => 'AR', 'name' => $greekStringConversion->grstrtoupper('Αργεντινή')),
                array('code' => 'AS', 'name' => $greekStringConversion->grstrtoupper('Αμερικανική Σαμόα')),
                array('code' => 'AT', 'name' => $greekStringConversion->grstrtoupper('Αυστρία')),
                array('code' => 'AU', 'name' => $greekStringConversion->grstrtoupper('Αυστραλία')),
                array('code' => 'AW', 'name' => $greekStringConversion->grstrtoupper('Αρούμπα')),
                array('code' => 'AX', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Όλαντ')),
                array('code' => 'AZ', 'name' => $greekStringConversion->grstrtoupper('Αζερμπαϊτζάν')),
                array('code' => 'BA', 'name' => $greekStringConversion->grstrtoupper('Βοσνία - Ερζεγοβίνη')),
                array('code' => 'BB', 'name' => $greekStringConversion->grstrtoupper('Μπαρμπάντος')),
                array('code' => 'BD', 'name' => $greekStringConversion->grstrtoupper('Μπανγκλαντές')),
                array('code' => 'BE', 'name' => $greekStringConversion->grstrtoupper('Βέλγιο')),
                array('code' => 'BF', 'name' => $greekStringConversion->grstrtoupper('Μπουρκίνα Φάσο')),
                array('code' => 'BG', 'name' => $greekStringConversion->grstrtoupper('Βουλγαρία')),
                array('code' => 'BH', 'name' => $greekStringConversion->grstrtoupper('Μπαχρέιν')),
                array('code' => 'BI', 'name' => $greekStringConversion->grstrtoupper('Μπουρούντι')),
                array('code' => 'BJ', 'name' => $greekStringConversion->grstrtoupper('Μπενίν')),
                array('code' => 'BL', 'name' => $greekStringConversion->grstrtoupper('Άγιος Βαρθολομαίος')),
                array('code' => 'BM', 'name' => $greekStringConversion->grstrtoupper('Βερμούδες')),
                array('code' => 'BN', 'name' => $greekStringConversion->grstrtoupper('Μπρουνέι')),
                array('code' => 'BO', 'name' => $greekStringConversion->grstrtoupper('Βολιβία')),
                array('code' => 'BQ', 'name' => $greekStringConversion->grstrtoupper('Ολλανδία Καραϊβικής')),
                array('code' => 'BR', 'name' => $greekStringConversion->grstrtoupper('Βραζιλία')),
                array('code' => 'BS', 'name' => $greekStringConversion->grstrtoupper('Μπαχάμες')),
                array('code' => 'BT', 'name' => $greekStringConversion->grstrtoupper('Μπουτάν')),
                array('code' => 'BW', 'name' => $greekStringConversion->grstrtoupper('Μποτσουάνα')),
                array('code' => 'BY', 'name' => $greekStringConversion->grstrtoupper('Λευκορωσία')),
                array('code' => 'BZ', 'name' => $greekStringConversion->grstrtoupper('Μπελίζ')),
                array('code' => 'CA', 'name' => $greekStringConversion->grstrtoupper('Καναδάς')),
                array('code' => 'CC', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Κόκος (Κίλινγκ)')),
                array('code' => 'CD', 'name' => $greekStringConversion->grstrtoupper('Κονγκό - Κινσάσα')),
                array('code' => 'CF', 'name' => $greekStringConversion->grstrtoupper('Κεντροαφρικανική Δημοκρατία')),
                array('code' => 'CG', 'name' => $greekStringConversion->grstrtoupper('Κονγκό - Μπραζαβίλ')),
                array('code' => 'CH', 'name' => $greekStringConversion->grstrtoupper('Ελβετία')),
                array('code' => 'CI', 'name' => $greekStringConversion->grstrtoupper('Ακτή Ελεφαντοστού')),
                array('code' => 'CK', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Κουκ')),
                array('code' => 'CL', 'name' => $greekStringConversion->grstrtoupper('Χιλή')),
                array('code' => 'CM', 'name' => $greekStringConversion->grstrtoupper('Καμερούν')),
                array('code' => 'CN', 'name' => $greekStringConversion->grstrtoupper('Κίνα')),
                array('code' => 'CO', 'name' => $greekStringConversion->grstrtoupper('Κολομβία')),
                array('code' => 'CR', 'name' => $greekStringConversion->grstrtoupper('Κόστα Ρίκα')),
                array('code' => 'CU', 'name' => $greekStringConversion->grstrtoupper('Κούβα')),
                array('code' => 'CV', 'name' => $greekStringConversion->grstrtoupper('Πράσινο Ακρωτήριο')),
                array('code' => 'CW', 'name' => $greekStringConversion->grstrtoupper('Κουρασάο')),
                array('code' => 'CX', 'name' => $greekStringConversion->grstrtoupper('Νήσος των Χριστουγέννων')),
                array('code' => 'CY', 'name' => $greekStringConversion->grstrtoupper('Κύπρος')),
                array('code' => 'CZ', 'name' => $greekStringConversion->grstrtoupper('Τσεχική Δημοκρατία')),
                array('code' => 'DE', 'name' => $greekStringConversion->grstrtoupper('Γερμανία')),
                array('code' => 'DG', 'name' => $greekStringConversion->grstrtoupper('Ντιέγκο Γκαρσία')),
                array('code' => 'DJ', 'name' => $greekStringConversion->grstrtoupper('Τζιμπουτί')),
                array('code' => 'DK', 'name' => $greekStringConversion->grstrtoupper('Δανία')),
                array('code' => 'DM', 'name' => $greekStringConversion->grstrtoupper('Ντομίνικα')),
                array('code' => 'DO', 'name' => $greekStringConversion->grstrtoupper('Δομινικανή Δημοκρατία')),
                array('code' => 'DZ', 'name' => $greekStringConversion->grstrtoupper('Αλγερία')),
                array('code' => 'EA', 'name' => $greekStringConversion->grstrtoupper('Θεούτα και Μελίλα')),
                array('code' => 'EC', 'name' => $greekStringConversion->grstrtoupper('Εκουαδόρ')),
                array('code' => 'EE', 'name' => $greekStringConversion->grstrtoupper('Εσθονία')),
                array('code' => 'EG', 'name' => $greekStringConversion->grstrtoupper('Αίγυπτος')),
                array('code' => 'EH', 'name' => $greekStringConversion->grstrtoupper('Δυτική Σαχάρα')),
                array('code' => 'ER', 'name' => $greekStringConversion->grstrtoupper('Ερυθραία')),
                array('code' => 'ES', 'name' => $greekStringConversion->grstrtoupper('Ισπανία')),
                array('code' => 'ET', 'name' => $greekStringConversion->grstrtoupper('Αιθιοπία')),
                array('code' => 'FI', 'name' => $greekStringConversion->grstrtoupper('Φινλανδία')),
                array('code' => 'FJ', 'name' => $greekStringConversion->grstrtoupper('Φίτζι')),
                array('code' => 'FK', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Φόκλαντ')),
                array('code' => 'FM', 'name' => $greekStringConversion->grstrtoupper('Μικρονησία')),
                array('code' => 'FO', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Φερόες')),
                array('code' => 'FR', 'name' => $greekStringConversion->grstrtoupper('Γαλλία')),
                array('code' => 'GA', 'name' => $greekStringConversion->grstrtoupper('Γκαμπόν')),
                array('code' => 'GB', 'name' => $greekStringConversion->grstrtoupper('Ηνωμένο Βασίλειο')),
                array('code' => 'GD', 'name' => $greekStringConversion->grstrtoupper('Γρενάδα')),
                array('code' => 'GE', 'name' => $greekStringConversion->grstrtoupper('Γεωργία')),
                array('code' => 'GF', 'name' => $greekStringConversion->grstrtoupper('Γαλλική Γουιάνα')),
                array('code' => 'GG', 'name' => $greekStringConversion->grstrtoupper('Γκέρνζι')),
                array('code' => 'GH', 'name' => $greekStringConversion->grstrtoupper('Γκάνα')),
                array('code' => 'GI', 'name' => $greekStringConversion->grstrtoupper('Γιβραλτάρ')),
                array('code' => 'GL', 'name' => $greekStringConversion->grstrtoupper('Γροιλανδία')),
                array('code' => 'GM', 'name' => $greekStringConversion->grstrtoupper('Γκάμπια')),
                array('code' => 'GN', 'name' => $greekStringConversion->grstrtoupper('Γουινέα')),
                array('code' => 'GP', 'name' => $greekStringConversion->grstrtoupper('Γουαδελούπη')),
                array('code' => 'GQ', 'name' => $greekStringConversion->grstrtoupper('Ισημερινή Γουινέα')),
                array('code' => 'GR', 'name' => $greekStringConversion->grstrtoupper('Ελλάδα')),
                array('code' => 'GS', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς')),
                array('code' => 'GT', 'name' => $greekStringConversion->grstrtoupper('Γουατεμάλα')),
                array('code' => 'GU', 'name' => $greekStringConversion->grstrtoupper('Γκουάμ')),
                array('code' => 'GW', 'name' => $greekStringConversion->grstrtoupper('Γουινέα Μπισάου')),
                array('code' => 'GY', 'name' => $greekStringConversion->grstrtoupper('Γουιάνα')),
                array('code' => 'HK', 'name' => $greekStringConversion->grstrtoupper('Χονγκ Κονγκ ΕΔΠ Κίνας')),
                array('code' => 'HN', 'name' => $greekStringConversion->grstrtoupper('Ονδούρα')),
                array('code' => 'HR', 'name' => $greekStringConversion->grstrtoupper('Κροατία')),
                array('code' => 'HT', 'name' => $greekStringConversion->grstrtoupper('Αϊτή')),
                array('code' => 'HU', 'name' => $greekStringConversion->grstrtoupper('Ουγγαρία')),
                array('code' => 'IC', 'name' => $greekStringConversion->grstrtoupper('Κανάριοι Νήσοι')),
                array('code' => 'ID', 'name' => $greekStringConversion->grstrtoupper('Ινδονησία')),
                array('code' => 'IE', 'name' => $greekStringConversion->grstrtoupper('Ιρλανδία')),
                array('code' => 'IL', 'name' => $greekStringConversion->grstrtoupper('Ισραήλ')),
                array('code' => 'IM', 'name' => $greekStringConversion->grstrtoupper('Νήσος Μαν')),
                array('code' => 'IN', 'name' => $greekStringConversion->grstrtoupper('Ινδία')),
                array('code' => 'IO', 'name' => $greekStringConversion->grstrtoupper('Βρετανικά Εδάφη Ινδικού Ωκεανού')),
                array('code' => 'IQ', 'name' => $greekStringConversion->grstrtoupper('Ιράκ')),
                array('code' => 'IR', 'name' => $greekStringConversion->grstrtoupper('Ιράν')),
                array('code' => 'IS', 'name' => $greekStringConversion->grstrtoupper('Ισλανδία')),
                array('code' => 'IT', 'name' => $greekStringConversion->grstrtoupper('Ιταλία')),
                array('code' => 'JE', 'name' => $greekStringConversion->grstrtoupper('Τζέρζι')),
                array('code' => 'JM', 'name' => $greekStringConversion->grstrtoupper('Τζαμάικα')),
                array('code' => 'JO', 'name' => $greekStringConversion->grstrtoupper('Ιορδανία')),
                array('code' => 'JP', 'name' => $greekStringConversion->grstrtoupper('Ιαπωνία')),
                array('code' => 'KE', 'name' => $greekStringConversion->grstrtoupper('Κένυα')),
                array('code' => 'KG', 'name' => $greekStringConversion->grstrtoupper('Κιργιστάν')),
                array('code' => 'KH', 'name' => $greekStringConversion->grstrtoupper('Καμπότζη')),
                array('code' => 'KI', 'name' => $greekStringConversion->grstrtoupper('Κιριμπάτι')),
                array('code' => 'KM', 'name' => $greekStringConversion->grstrtoupper('Κομόρες')),
                array('code' => 'KN', 'name' => $greekStringConversion->grstrtoupper('Άγιος Χριστόφορος και Νέβις')),
                array('code' => 'KP', 'name' => $greekStringConversion->grstrtoupper('Βόρεια Κορέα')),
                array('code' => 'KR', 'name' => $greekStringConversion->grstrtoupper('Νότια Κορέα')),
                array('code' => 'KW', 'name' => $greekStringConversion->grstrtoupper('Κουβέιτ')),
                array('code' => 'KY', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Κάιμαν')),
                array('code' => 'KZ', 'name' => $greekStringConversion->grstrtoupper('Καζακστάν')),
                array('code' => 'LA', 'name' => $greekStringConversion->grstrtoupper('Λάος')),
                array('code' => 'LB', 'name' => $greekStringConversion->grstrtoupper('Λίβανος')),
                array('code' => 'LC', 'name' => $greekStringConversion->grstrtoupper('Αγία Λουκία')),
                array('code' => 'LI', 'name' => $greekStringConversion->grstrtoupper('Λιχτενστάιν')),
                array('code' => 'LK', 'name' => $greekStringConversion->grstrtoupper('Σρι Λάνκα')),
                array('code' => 'LR', 'name' => $greekStringConversion->grstrtoupper('Λιβερία')),
                array('code' => 'LS', 'name' => $greekStringConversion->grstrtoupper('Λεσότο')),
                array('code' => 'LT', 'name' => $greekStringConversion->grstrtoupper('Λιθουανία')),
                array('code' => 'LU', 'name' => $greekStringConversion->grstrtoupper('Λουξεμβούργο')),
                array('code' => 'LV', 'name' => $greekStringConversion->grstrtoupper('Λετονία')),
                array('code' => 'LY', 'name' => $greekStringConversion->grstrtoupper('Λιβύη')),
                array('code' => 'MA', 'name' => $greekStringConversion->grstrtoupper('Μαρόκο')),
                array('code' => 'MC', 'name' => $greekStringConversion->grstrtoupper('Μονακό')),
                array('code' => 'MD', 'name' => $greekStringConversion->grstrtoupper('Μολδαβία')),
                array('code' => 'ME', 'name' => $greekStringConversion->grstrtoupper('Μαυροβούνιο')),
                array('code' => 'MF', 'name' => $greekStringConversion->grstrtoupper('Άγιος Μαρτίνος (Γαλλικό τμήμα)')),
                array('code' => 'MG', 'name' => $greekStringConversion->grstrtoupper('Μαδαγασκάρη')),
                array('code' => 'MH', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Μάρσαλ')),
                array('code' => 'MK', 'name' => $greekStringConversion->grstrtoupper('Πρώην Γιουγκοσλαβική Δημοκρατία της Μακεδονίας')),
                array('code' => 'ML', 'name' => $greekStringConversion->grstrtoupper('Μάλι')),
                array('code' => 'MM', 'name' => $greekStringConversion->grstrtoupper('Μιανμάρ/Βιρμανία')),
                array('code' => 'MN', 'name' => $greekStringConversion->grstrtoupper('Μογγολία')),
                array('code' => 'MO', 'name' => $greekStringConversion->grstrtoupper('Μακάο ΕΔΠ Κίνας')),
                array('code' => 'MP', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Βόρειες Μαριάνες')),
                array('code' => 'MQ', 'name' => $greekStringConversion->grstrtoupper('Μαρτινίκα')),
                array('code' => 'MR', 'name' => $greekStringConversion->grstrtoupper('Μαυριτανία')),
                array('code' => 'MS', 'name' => $greekStringConversion->grstrtoupper('Μονσεράτ')),
                array('code' => 'MT', 'name' => $greekStringConversion->grstrtoupper('Μάλτα')),
                array('code' => 'MU', 'name' => $greekStringConversion->grstrtoupper('Μαυρίκιος')),
                array('code' => 'MV', 'name' => $greekStringConversion->grstrtoupper('Μαλδίβες')),
                array('code' => 'MW', 'name' => $greekStringConversion->grstrtoupper('Μαλάουι')),
                array('code' => 'MX', 'name' => $greekStringConversion->grstrtoupper('Μεξικό')),
                array('code' => 'MY', 'name' => $greekStringConversion->grstrtoupper('Μαλαισία')),
                array('code' => 'MZ', 'name' => $greekStringConversion->grstrtoupper('Μοζαμβίκη')),
                array('code' => 'NA', 'name' => $greekStringConversion->grstrtoupper('Ναμίμπια')),
                array('code' => 'NC', 'name' => $greekStringConversion->grstrtoupper('Νέα Καληδονία')),
                array('code' => 'NE', 'name' => $greekStringConversion->grstrtoupper('Νίγηρας')),
                array('code' => 'NF', 'name' => $greekStringConversion->grstrtoupper('Νήσος Νόρφολκ')),
                array('code' => 'NG', 'name' => $greekStringConversion->grstrtoupper('Νιγηρία')),
                array('code' => 'NI', 'name' => $greekStringConversion->grstrtoupper('Νικαράγουα')),
                array('code' => 'NL', 'name' => $greekStringConversion->grstrtoupper('Ολλανδία')),
                array('code' => 'NO', 'name' => $greekStringConversion->grstrtoupper('Νορβηγία')),
                array('code' => 'NP', 'name' => $greekStringConversion->grstrtoupper('Νεπάλ')),
                array('code' => 'NR', 'name' => $greekStringConversion->grstrtoupper('Ναουρού')),
                array('code' => 'NU', 'name' => $greekStringConversion->grstrtoupper('Νιούε')),
                array('code' => 'NZ', 'name' => $greekStringConversion->grstrtoupper('Νέα Ζηλανδία')),
                array('code' => 'OM', 'name' => $greekStringConversion->grstrtoupper('Ομάν')),
                array('code' => 'PA', 'name' => $greekStringConversion->grstrtoupper('Παναμάς')),
                array('code' => 'PE', 'name' => $greekStringConversion->grstrtoupper('Περού')),
                array('code' => 'PF', 'name' => $greekStringConversion->grstrtoupper('Γαλλική Πολυνησία')),
                array('code' => 'PG', 'name' => $greekStringConversion->grstrtoupper('Παπούα Νέα Γουινέα')),
                array('code' => 'PH', 'name' => $greekStringConversion->grstrtoupper('Φιλιππίνες')),
                array('code' => 'PK', 'name' => $greekStringConversion->grstrtoupper('Πακιστάν')),
                array('code' => 'PL', 'name' => $greekStringConversion->grstrtoupper('Πολωνία')),
                array('code' => 'PM', 'name' => $greekStringConversion->grstrtoupper('Σεν Πιερ και Μικελόν')),
                array('code' => 'PN', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Πίτκερν')),
                array('code' => 'PR', 'name' => $greekStringConversion->grstrtoupper('Πουέρτο Ρίκο')),
                array('code' => 'PS', 'name' => $greekStringConversion->grstrtoupper('Παλαιστινιακά Εδάφη')),
                array('code' => 'PT', 'name' => $greekStringConversion->grstrtoupper('Πορτογαλία')),
                array('code' => 'PW', 'name' => $greekStringConversion->grstrtoupper('Παλάου')),
                array('code' => 'PY', 'name' => $greekStringConversion->grstrtoupper('Παραγουάη')),
                array('code' => 'QA', 'name' => $greekStringConversion->grstrtoupper('Κατάρ')),
                array('code' => 'RE', 'name' => $greekStringConversion->grstrtoupper('Ρεϊνιόν')),
                array('code' => 'RO', 'name' => $greekStringConversion->grstrtoupper('Ρουμανία')),
                array('code' => 'RS', 'name' => $greekStringConversion->grstrtoupper('Σερβία')),
                array('code' => 'RU', 'name' => $greekStringConversion->grstrtoupper('Ρωσία')),
                array('code' => 'RW', 'name' => $greekStringConversion->grstrtoupper('Ρουάντα')),
                array('code' => 'SA', 'name' => $greekStringConversion->grstrtoupper('Σαουδική Αραβία')),
                array('code' => 'SB', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Σολομώντος')),
                array('code' => 'SC', 'name' => $greekStringConversion->grstrtoupper('Σεϋχέλλες')),
                array('code' => 'SD', 'name' => $greekStringConversion->grstrtoupper('Σουδάν')),
                array('code' => 'SE', 'name' => $greekStringConversion->grstrtoupper('Σουηδία')),
                array('code' => 'SG', 'name' => $greekStringConversion->grstrtoupper('Σιγκαπούρη')),
                array('code' => 'SH', 'name' => $greekStringConversion->grstrtoupper('Αγία Ελένη')),
                array('code' => 'SI', 'name' => $greekStringConversion->grstrtoupper('Σλοβενία')),
                array('code' => 'SJ', 'name' => $greekStringConversion->grstrtoupper('Σβάλμπαρντ και Γιαν Μαγιέν')),
                array('code' => 'SK', 'name' => $greekStringConversion->grstrtoupper('Σλοβακία')),
                array('code' => 'SL', 'name' => $greekStringConversion->grstrtoupper('Σιέρα Λεόνε')),
                array('code' => 'SM', 'name' => $greekStringConversion->grstrtoupper('Άγιος Μαρίνος')),
                array('code' => 'SN', 'name' => $greekStringConversion->grstrtoupper('Σενεγάλη')),
                array('code' => 'SO', 'name' => $greekStringConversion->grstrtoupper('Σομαλία')),
                array('code' => 'SR', 'name' => $greekStringConversion->grstrtoupper('Σουρινάμ')),
                array('code' => 'SS', 'name' => $greekStringConversion->grstrtoupper('Νότιο Σουδάν')),
                array('code' => 'ST', 'name' => $greekStringConversion->grstrtoupper('Σάο Τομέ και Πρίνσιπε')),
                array('code' => 'SV', 'name' => $greekStringConversion->grstrtoupper('Ελ Σαλβαδόρ')),
                array('code' => 'SX', 'name' => $greekStringConversion->grstrtoupper('Άγιος Μαρτίνος (Ολλανδικό τμήμα)')),
                array('code' => 'SY', 'name' => $greekStringConversion->grstrtoupper('Συρία')),
                array('code' => 'SZ', 'name' => $greekStringConversion->grstrtoupper('Σουαζιλάνδη')),
                array('code' => 'TA', 'name' => $greekStringConversion->grstrtoupper('Τριστάν ντα Κούνια')),
                array('code' => 'TC', 'name' => $greekStringConversion->grstrtoupper('Νήσοι Τερκ και Κάικος')),
                array('code' => 'TD', 'name' => $greekStringConversion->grstrtoupper('Τσαντ')),
                array('code' => 'TF', 'name' => $greekStringConversion->grstrtoupper('Γαλλικές περιοχές του νοτίου ημισφαιρίου')),
                array('code' => 'TG', 'name' => $greekStringConversion->grstrtoupper('Τόγκο')),
                array('code' => 'TH', 'name' => $greekStringConversion->grstrtoupper('Ταϊλάνδη')),
                array('code' => 'TJ', 'name' => $greekStringConversion->grstrtoupper('Τατζικιστάν')),
                array('code' => 'TK', 'name' => $greekStringConversion->grstrtoupper('Τοκελάου')),
                array('code' => 'TL', 'name' => $greekStringConversion->grstrtoupper('Τιμόρ-Λέστε')),
                array('code' => 'TM', 'name' => $greekStringConversion->grstrtoupper('Τουρκμενιστάν')),
                array('code' => 'TN', 'name' => $greekStringConversion->grstrtoupper('Τυνησία')),
                array('code' => 'TO', 'name' => $greekStringConversion->grstrtoupper('Τόνγκα')),
                array('code' => 'TR', 'name' => $greekStringConversion->grstrtoupper('Τουρκία')),
                array('code' => 'TT', 'name' => $greekStringConversion->grstrtoupper('Τρινιντάντ και Τομπάγκο')),
                array('code' => 'TV', 'name' => $greekStringConversion->grstrtoupper('Τουβαλού')),
                array('code' => 'TW', 'name' => $greekStringConversion->grstrtoupper('Ταϊβάν')),
                array('code' => 'TZ', 'name' => $greekStringConversion->grstrtoupper('Τανζανία')),
                array('code' => 'UA', 'name' => $greekStringConversion->grstrtoupper('Ουκρανία')),
                array('code' => 'UG', 'name' => $greekStringConversion->grstrtoupper('Ουγκάντα')),
                array('code' => 'UM', 'name' => $greekStringConversion->grstrtoupper('Απομακρυσμένες Νησίδες Η.Π.Α.')),
                array('code' => 'US', 'name' => $greekStringConversion->grstrtoupper('Ηνωμένες Πολιτείες')),
                array('code' => 'UY', 'name' => $greekStringConversion->grstrtoupper('Ουρουγουάη')),
                array('code' => 'UZ', 'name' => $greekStringConversion->grstrtoupper('Ουζμπεκιστάν')),
                array('code' => 'VA', 'name' => $greekStringConversion->grstrtoupper('Βατικανό')),
                array('code' => 'VC', 'name' => $greekStringConversion->grstrtoupper('Άγιος Βικέντιος και Γρεναδίνες')),
                array('code' => 'VE', 'name' => $greekStringConversion->grstrtoupper('Βενεζουέλα')),
                array('code' => 'VG', 'name' => $greekStringConversion->grstrtoupper('Βρετανικές Παρθένοι Νήσοι')),
                array('code' => 'VI', 'name' => $greekStringConversion->grstrtoupper('Αμερικανικές Παρθένοι Νήσοι')),
                array('code' => 'VN', 'name' => $greekStringConversion->grstrtoupper('Βιετνάμ')),
                array('code' => 'VU', 'name' => $greekStringConversion->grstrtoupper('Βανουάτου')),
                array('code' => 'WF', 'name' => $greekStringConversion->grstrtoupper('Ουάλις και Φουτούνα')),
                array('code' => 'WS', 'name' => $greekStringConversion->grstrtoupper('Σαμόα')),
                array('code' => 'XK', 'name' => $greekStringConversion->grstrtoupper('Κόσοβο')),
                array('code' => 'YE', 'name' => $greekStringConversion->grstrtoupper('Υεμένη')),
                array('code' => 'YT', 'name' => $greekStringConversion->grstrtoupper('Μαγιότ')),
                array('code' => 'ZA', 'name' => $greekStringConversion->grstrtoupper('Νότια Αφρική')),
                array('code' => 'ZM', 'name' => $greekStringConversion->grstrtoupper('Ζάμπια')),
                array('code' => 'ZW', 'name' => $greekStringConversion->grstrtoupper('Ζιμπάμπουε')),
            )
        );
    }
}
