<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CountriesLookupSeeder extends Seeder
{
    public function run()
    {
        \DB::table('countries_lookup')->insert(
            array(
                array('code' => 'AC', 'name' => 'Νήσος Ασενσιόν'),
                array('code' => 'AD', 'name' => 'Ανδόρα'),
                array('code' => 'AE', 'name' => 'Ηνωμένα Αραβικά Εμιράτα'),
                array('code' => 'AF', 'name' => 'Αφγανιστάν'),
                array('code' => 'AG', 'name' => 'Αντίγκουα και Μπαρμπούντα'),
                array('code' => 'AI', 'name' => 'Ανγκουίλα'),
                array('code' => 'AL', 'name' => 'Αλβανία'),
                array('code' => 'AM', 'name' => 'Αρμενία'),
                array('code' => 'AO', 'name' => 'Ανγκόλα'),
                array('code' => 'AQ', 'name' => 'Ανταρκτική'),
                array('code' => 'AR', 'name' => 'Αργεντινή'),
                array('code' => 'AS', 'name' => 'Αμερικανική Σαμόα'),
                array('code' => 'AT', 'name' => 'Αυστρία'),
                array('code' => 'AU', 'name' => 'Αυστραλία'),
                array('code' => 'AW', 'name' => 'Αρούμπα'),
                array('code' => 'AX', 'name' => 'Νήσοι Όλαντ'),
                array('code' => 'AZ', 'name' => 'Αζερμπαϊτζάν'),
                array('code' => 'BA', 'name' => 'Βοσνία - Ερζεγοβίνη'),
                array('code' => 'BB', 'name' => 'Μπαρμπάντος'),
                array('code' => 'BD', 'name' => 'Μπανγκλαντές'),
                array('code' => 'BE', 'name' => 'Βέλγιο'),
                array('code' => 'BF', 'name' => 'Μπουρκίνα Φάσο'),
                array('code' => 'BG', 'name' => 'Βουλγαρία'),
                array('code' => 'BH', 'name' => 'Μπαχρέιν'),
                array('code' => 'BI', 'name' => 'Μπουρούντι'),
                array('code' => 'BJ', 'name' => 'Μπενίν'),
                array('code' => 'BL', 'name' => 'Άγιος Βαρθολομαίος'),
                array('code' => 'BM', 'name' => 'Βερμούδες'),
                array('code' => 'BN', 'name' => 'Μπρουνέι'),
                array('code' => 'BO', 'name' => 'Βολιβία'),
                array('code' => 'BQ', 'name' => 'Ολλανδία Καραϊβικής'),
                array('code' => 'BR', 'name' => 'Βραζιλία'),
                array('code' => 'BS', 'name' => 'Μπαχάμες'),
                array('code' => 'BT', 'name' => 'Μπουτάν'),
                array('code' => 'BW', 'name' => 'Μποτσουάνα'),
                array('code' => 'BY', 'name' => 'Λευκορωσία'),
                array('code' => 'BZ', 'name' => 'Μπελίζ'),
                array('code' => 'CA', 'name' => 'Καναδάς'),
                array('code' => 'CC', 'name' => 'Νήσοι Κόκος (Κίλινγκ)'),
                array('code' => 'CD', 'name' => 'Κονγκό - Κινσάσα'),
                array('code' => 'CF', 'name' => 'Κεντροαφρικανική Δημοκρατία'),
                array('code' => 'CG', 'name' => 'Κονγκό - Μπραζαβίλ'),
                array('code' => 'CH', 'name' => 'Ελβετία'),
                array('code' => 'CI', 'name' => 'Ακτή Ελεφαντοστού'),
                array('code' => 'CK', 'name' => 'Νήσοι Κουκ'),
                array('code' => 'CL', 'name' => 'Χιλή'),
                array('code' => 'CM', 'name' => 'Καμερούν'),
                array('code' => 'CN', 'name' => 'Κίνα'),
                array('code' => 'CO', 'name' => 'Κολομβία'),
                array('code' => 'CR', 'name' => 'Κόστα Ρίκα'),
                array('code' => 'CU', 'name' => 'Κούβα'),
                array('code' => 'CV', 'name' => 'Πράσινο Ακρωτήριο'),
                array('code' => 'CW', 'name' => 'Κουρασάο'),
                array('code' => 'CX', 'name' => 'Νήσος των Χριστουγέννων'),
                array('code' => 'CY', 'name' => 'Κύπρος'),
                array('code' => 'CZ', 'name' => 'Τσεχική Δημοκρατία'),
                array('code' => 'DE', 'name' => 'Γερμανία'),
                array('code' => 'DG', 'name' => 'Ντιέγκο Γκαρσία'),
                array('code' => 'DJ', 'name' => 'Τζιμπουτί'),
                array('code' => 'DK', 'name' => 'Δανία'),
                array('code' => 'DM', 'name' => 'Ντομίνικα'),
                array('code' => 'DO', 'name' => 'Δομινικανή Δημοκρατία'),
                array('code' => 'DZ', 'name' => 'Αλγερία'),
                array('code' => 'EA', 'name' => 'Θεούτα και Μελίλα'),
                array('code' => 'EC', 'name' => 'Εκουαδόρ'),
                array('code' => 'EE', 'name' => 'Εσθονία'),
                array('code' => 'EG', 'name' => 'Αίγυπτος'),
                array('code' => 'EH', 'name' => 'Δυτική Σαχάρα'),
                array('code' => 'ER', 'name' => 'Ερυθραία'),
                array('code' => 'ES', 'name' => 'Ισπανία'),
                array('code' => 'ET', 'name' => 'Αιθιοπία'),
                array('code' => 'FI', 'name' => 'Φινλανδία'),
                array('code' => 'FJ', 'name' => 'Φίτζι'),
                array('code' => 'FK', 'name' => 'Νήσοι Φόκλαντ'),
                array('code' => 'FM', 'name' => 'Μικρονησία'),
                array('code' => 'FO', 'name' => 'Νήσοι Φερόες'),
                array('code' => 'FR', 'name' => 'Γαλλία'),
                array('code' => 'GA', 'name' => 'Γκαμπόν'),
                array('code' => 'GB', 'name' => 'Ηνωμένο Βασίλειο'),
                array('code' => 'GD', 'name' => 'Γρενάδα'),
                array('code' => 'GE', 'name' => 'Γεωργία'),
                array('code' => 'GF', 'name' => 'Γαλλική Γουιάνα'),
                array('code' => 'GG', 'name' => 'Γκέρνζι'),
                array('code' => 'GH', 'name' => 'Γκάνα'),
                array('code' => 'GI', 'name' => 'Γιβραλτάρ'),
                array('code' => 'GL', 'name' => 'Γροιλανδία'),
                array('code' => 'GM', 'name' => 'Γκάμπια'),
                array('code' => 'GN', 'name' => 'Γουινέα'),
                array('code' => 'GP', 'name' => 'Γουαδελούπη'),
                array('code' => 'GQ', 'name' => 'Ισημερινή Γουινέα'),
                array('code' => 'GR', 'name' => 'Ελλάδα'),
                array('code' => 'GS', 'name' => 'Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς'),
                array('code' => 'GT', 'name' => 'Γουατεμάλα'),
                array('code' => 'GU', 'name' => 'Γκουάμ'),
                array('code' => 'GW', 'name' => 'Γουινέα Μπισάου'),
                array('code' => 'GY', 'name' => 'Γουιάνα'),
                array('code' => 'HK', 'name' => 'Χονγκ Κονγκ ΕΔΠ Κίνας'),
                array('code' => 'HN', 'name' => 'Ονδούρα'),
                array('code' => 'HR', 'name' => 'Κροατία'),
                array('code' => 'HT', 'name' => 'Αϊτή'),
                array('code' => 'HU', 'name' => 'Ουγγαρία'),
                array('code' => 'IC', 'name' => 'Κανάριοι Νήσοι'),
                array('code' => 'ID', 'name' => 'Ινδονησία'),
                array('code' => 'IE', 'name' => 'Ιρλανδία'),
                array('code' => 'IL', 'name' => 'Ισραήλ'),
                array('code' => 'IM', 'name' => 'Νήσος Μαν'),
                array('code' => 'IN', 'name' => 'Ινδία'),
                array('code' => 'IO', 'name' => 'Βρετανικά Εδάφη Ινδικού Ωκεανού'),
                array('code' => 'IQ', 'name' => 'Ιράκ'),
                array('code' => 'IR', 'name' => 'Ιράν'),
                array('code' => 'IS', 'name' => 'Ισλανδία'),
                array('code' => 'IT', 'name' => 'Ιταλία'),
                array('code' => 'JE', 'name' => 'Τζέρζι'),
                array('code' => 'JM', 'name' => 'Τζαμάικα'),
                array('code' => 'JO', 'name' => 'Ιορδανία'),
                array('code' => 'JP', 'name' => 'Ιαπωνία'),
                array('code' => 'KE', 'name' => 'Κένυα'),
                array('code' => 'KG', 'name' => 'Κιργιστάν'),
                array('code' => 'KH', 'name' => 'Καμπότζη'),
                array('code' => 'KI', 'name' => 'Κιριμπάτι'),
                array('code' => 'KM', 'name' => 'Κομόρες'),
                array('code' => 'KN', 'name' => 'Άγιος Χριστόφορος και Νέβις'),
                array('code' => 'KP', 'name' => 'Βόρεια Κορέα'),
                array('code' => 'KR', 'name' => 'Νότια Κορέα'),
                array('code' => 'KW', 'name' => 'Κουβέιτ'),
                array('code' => 'KY', 'name' => 'Νήσοι Κάιμαν'),
                array('code' => 'KZ', 'name' => 'Καζακστάν'),
                array('code' => 'LA', 'name' => 'Λάος'),
                array('code' => 'LB', 'name' => 'Λίβανος'),
                array('code' => 'LC', 'name' => 'Αγία Λουκία'),
                array('code' => 'LI', 'name' => 'Λιχτενστάιν'),
                array('code' => 'LK', 'name' => 'Σρι Λάνκα'),
                array('code' => 'LR', 'name' => 'Λιβερία'),
                array('code' => 'LS', 'name' => 'Λεσότο'),
                array('code' => 'LT', 'name' => 'Λιθουανία'),
                array('code' => 'LU', 'name' => 'Λουξεμβούργο'),
                array('code' => 'LV', 'name' => 'Λετονία'),
                array('code' => 'LY', 'name' => 'Λιβύη'),
                array('code' => 'MA', 'name' => 'Μαρόκο'),
                array('code' => 'MC', 'name' => 'Μονακό'),
                array('code' => 'MD', 'name' => 'Μολδαβία'),
                array('code' => 'ME', 'name' => 'Μαυροβούνιο'),
                array('code' => 'MF', 'name' => 'Άγιος Μαρτίνος (Γαλλικό τμήμα)'),
                array('code' => 'MG', 'name' => 'Μαδαγασκάρη'),
                array('code' => 'MH', 'name' => 'Νήσοι Μάρσαλ'),
                array('code' => 'MK', 'name' => 'Πρώην Γιουγκοσλαβική Δημοκρατία της Μακεδονίας'),
                array('code' => 'ML', 'name' => 'Μάλι'),
                array('code' => 'MM', 'name' => 'Μιανμάρ/Βιρμανία'),
                array('code' => 'MN', 'name' => 'Μογγολία'),
                array('code' => 'MO', 'name' => 'Μακάο ΕΔΠ Κίνας'),
                array('code' => 'MP', 'name' => 'Νήσοι Βόρειες Μαριάνες'),
                array('code' => 'MQ', 'name' => 'Μαρτινίκα'),
                array('code' => 'MR', 'name' => 'Μαυριτανία'),
                array('code' => 'MS', 'name' => 'Μονσεράτ'),
                array('code' => 'MT', 'name' => 'Μάλτα'),
                array('code' => 'MU', 'name' => 'Μαυρίκιος'),
                array('code' => 'MV', 'name' => 'Μαλδίβες'),
                array('code' => 'MW', 'name' => 'Μαλάουι'),
                array('code' => 'MX', 'name' => 'Μεξικό'),
                array('code' => 'MY', 'name' => 'Μαλαισία'),
                array('code' => 'MZ', 'name' => 'Μοζαμβίκη'),
                array('code' => 'NA', 'name' => 'Ναμίμπια'),
                array('code' => 'NC', 'name' => 'Νέα Καληδονία'),
                array('code' => 'NE', 'name' => 'Νίγηρας'),
                array('code' => 'NF', 'name' => 'Νήσος Νόρφολκ'),
                array('code' => 'NG', 'name' => 'Νιγηρία'),
                array('code' => 'NI', 'name' => 'Νικαράγουα'),
                array('code' => 'NL', 'name' => 'Ολλανδία'),
                array('code' => 'NO', 'name' => 'Νορβηγία'),
                array('code' => 'NP', 'name' => 'Νεπάλ'),
                array('code' => 'NR', 'name' => 'Ναουρού'),
                array('code' => 'NU', 'name' => 'Νιούε'),
                array('code' => 'NZ', 'name' => 'Νέα Ζηλανδία'),
                array('code' => 'OM', 'name' => 'Ομάν'),
                array('code' => 'PA', 'name' => 'Παναμάς'),
                array('code' => 'PE', 'name' => 'Περού'),
                array('code' => 'PF', 'name' => 'Γαλλική Πολυνησία'),
                array('code' => 'PG', 'name' => 'Παπούα Νέα Γουινέα'),
                array('code' => 'PH', 'name' => 'Φιλιππίνες'),
                array('code' => 'PK', 'name' => 'Πακιστάν'),
                array('code' => 'PL', 'name' => 'Πολωνία'),
                array('code' => 'PM', 'name' => 'Σεν Πιερ και Μικελόν'),
                array('code' => 'PN', 'name' => 'Νήσοι Πίτκερν'),
                array('code' => 'PR', 'name' => 'Πουέρτο Ρίκο'),
                array('code' => 'PS', 'name' => 'Παλαιστινιακά Εδάφη'),
                array('code' => 'PT', 'name' => 'Πορτογαλία'),
                array('code' => 'PW', 'name' => 'Παλάου'),
                array('code' => 'PY', 'name' => 'Παραγουάη'),
                array('code' => 'QA', 'name' => 'Κατάρ'),
                array('code' => 'RE', 'name' => 'Ρεϊνιόν'),
                array('code' => 'RO', 'name' => 'Ρουμανία'),
                array('code' => 'RS', 'name' => 'Σερβία'),
                array('code' => 'RU', 'name' => 'Ρωσία'),
                array('code' => 'RW', 'name' => 'Ρουάντα'),
                array('code' => 'SA', 'name' => 'Σαουδική Αραβία'),
                array('code' => 'SB', 'name' => 'Νήσοι Σολομώντος'),
                array('code' => 'SC', 'name' => 'Σεϋχέλλες'),
                array('code' => 'SD', 'name' => 'Σουδάν'),
                array('code' => 'SE', 'name' => 'Σουηδία'),
                array('code' => 'SG', 'name' => 'Σιγκαπούρη'),
                array('code' => 'SH', 'name' => 'Αγία Ελένη'),
                array('code' => 'SI', 'name' => 'Σλοβενία'),
                array('code' => 'SJ', 'name' => 'Σβάλμπαρντ και Γιαν Μαγιέν'),
                array('code' => 'SK', 'name' => 'Σλοβακία'),
                array('code' => 'SL', 'name' => 'Σιέρα Λεόνε'),
                array('code' => 'SM', 'name' => 'Άγιος Μαρίνος'),
                array('code' => 'SN', 'name' => 'Σενεγάλη'),
                array('code' => 'SO', 'name' => 'Σομαλία'),
                array('code' => 'SR', 'name' => 'Σουρινάμ'),
                array('code' => 'SS', 'name' => 'Νότιο Σουδάν'),
                array('code' => 'ST', 'name' => 'Σάο Τομέ και Πρίνσιπε'),
                array('code' => 'SV', 'name' => 'Ελ Σαλβαδόρ'),
                array('code' => 'SX', 'name' => 'Άγιος Μαρτίνος (Ολλανδικό τμήμα)'),
                array('code' => 'SY', 'name' => 'Συρία'),
                array('code' => 'SZ', 'name' => 'Σουαζιλάνδη'),
                array('code' => 'TA', 'name' => 'Τριστάν ντα Κούνια'),
                array('code' => 'TC', 'name' => 'Νήσοι Τερκ και Κάικος'),
                array('code' => 'TD', 'name' => 'Τσαντ'),
                array('code' => 'TF', 'name' => 'Γαλλικές περιοχές του νοτίου ημισφαιρίου'),
                array('code' => 'TG', 'name' => 'Τόγκο'),
                array('code' => 'TH', 'name' => 'Ταϊλάνδη'),
                array('code' => 'TJ', 'name' => 'Τατζικιστάν'),
                array('code' => 'TK', 'name' => 'Τοκελάου'),
                array('code' => 'TL', 'name' => 'Τιμόρ-Λέστε'),
                array('code' => 'TM', 'name' => 'Τουρκμενιστάν'),
                array('code' => 'TN', 'name' => 'Τυνησία'),
                array('code' => 'TO', 'name' => 'Τόνγκα'),
                array('code' => 'TR', 'name' => 'Τουρκία'),
                array('code' => 'TT', 'name' => 'Τρινιντάντ και Τομπάγκο'),
                array('code' => 'TV', 'name' => 'Τουβαλού'),
                array('code' => 'TW', 'name' => 'Ταϊβάν'),
                array('code' => 'TZ', 'name' => 'Τανζανία'),
                array('code' => 'UA', 'name' => 'Ουκρανία'),
                array('code' => 'UG', 'name' => 'Ουγκάντα'),
                array('code' => 'UM', 'name' => 'Απομακρυσμένες Νησίδες Η.Π.Α.'),
                array('code' => 'US', 'name' => 'Ηνωμένες Πολιτείες'),
                array('code' => 'UY', 'name' => 'Ουρουγουάη'),
                array('code' => 'UZ', 'name' => 'Ουζμπεκιστάν'),
                array('code' => 'VA', 'name' => 'Βατικανό'),
                array('code' => 'VC', 'name' => 'Άγιος Βικέντιος και Γρεναδίνες'),
                array('code' => 'VE', 'name' => 'Βενεζουέλα'),
                array('code' => 'VG', 'name' => 'Βρετανικές Παρθένοι Νήσοι'),
                array('code' => 'VI', 'name' => 'Αμερικανικές Παρθένοι Νήσοι'),
                array('code' => 'VN', 'name' => 'Βιετνάμ'),
                array('code' => 'VU', 'name' => 'Βανουάτου'),
                array('code' => 'WF', 'name' => 'Ουάλις και Φουτούνα'),
                array('code' => 'WS', 'name' => 'Σαμόα'),
                array('code' => 'XK', 'name' => 'Κόσοβο'),
                array('code' => 'YE', 'name' => 'Υεμένη'),
                array('code' => 'YT', 'name' => 'Μαγιότ'),
                array('code' => 'ZA', 'name' => 'Νότια Αφρική'),
                array('code' => 'ZM', 'name' => 'Ζάμπια'),
                array('code' => 'ZW', 'name' => 'Ζιμπάμπουε'),
            )
        );
    }
}
