<?php

use Illuminate\Database\Seeder;


class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $greekStringConversion = new \App\Services\GreekStringConversionHelper();
        \DB::table('languages')->insert(
            array(
                array('code' => '---', 'name' => 'Επιλέξτε γλώσσα'),
                array('code' => 'abq', 'name' => $greekStringConversion->grstrtoupper('Αβαζικά')),
                array('code' => 'av', 'name' => $greekStringConversion->grstrtoupper('Αβαρικά')),
                array('code' => 'en', 'name' => $greekStringConversion->grstrtoupper('Αγγλικά')),
                array('code' => 'ady', 'name' => $greekStringConversion->grstrtoupper('Αδυγικά')),
                array('code' => 'az', 'name' => $greekStringConversion->grstrtoupper('Αζερικά')),
                array('code' => 'ht', 'name' => $greekStringConversion->grstrtoupper('Αϊτικά')),
                array('code' => 'ak', 'name' => $greekStringConversion->grstrtoupper('Άκαν')),
                array('code' => 'sq', 'name' => $greekStringConversion->grstrtoupper('Αλβανικά')),
                array('code' => 'ale', 'name' => $greekStringConversion->grstrtoupper('Αλεουτικά')),
                array('code' => 'am', 'name' => $greekStringConversion->grstrtoupper('Αμαρικά')),
                array('code' => 'ab', 'name' => $greekStringConversion->grstrtoupper('Αμπχαζικά')),
                array('code' => 'hsb', 'name' => $greekStringConversion->grstrtoupper('Άνω Σορβικά')),
                array('code' => 'ar', 'name' => $greekStringConversion->grstrtoupper('Αραβικά')),
                array('code' => 'an', 'name' => $greekStringConversion->grstrtoupper('Αραγονικά')),
                array('code' => 'hy', 'name' => $greekStringConversion->grstrtoupper('Αρμένικα')),
                array('code' => 'aae', 'name' => $greekStringConversion->grstrtoupper('Αρμπερές')),
                array('code' => 'grc', 'name' => $greekStringConversion->grstrtoupper('Ἀρχαῖα Ἑλληνικά')),
                array('code' => 'as', 'name' => $greekStringConversion->grstrtoupper('Ασαμικά')),
                array('code' => 'mey', 'name' => $greekStringConversion->grstrtoupper('Ασσανικά')),
                array('code' => 'ast', 'name' => $greekStringConversion->grstrtoupper('Αστουρικά')),
                array('code' => 'ay', 'name' => $greekStringConversion->grstrtoupper('Αϋμαρικά')),
                array('code' => 'aa', 'name' => $greekStringConversion->grstrtoupper('Αφάρ')),
                array('code' => 'af', 'name' => $greekStringConversion->grstrtoupper('Αφρικανικά')),
                array('code' => 'wa', 'name' => $greekStringConversion->grstrtoupper('Βαλλονικά')),
                array('code' => 'bal', 'name' => $greekStringConversion->grstrtoupper('Βαλουχικά')),
                array('code' => 'bm', 'name' => $greekStringConversion->grstrtoupper('Βαμβαρικά')),
                array('code' => 'bcj', 'name' => $greekStringConversion->grstrtoupper('Βαρδικά')),
                array('code' => 'eu', 'name' => $greekStringConversion->grstrtoupper('Βασκικά')),
                array('code' => 'ba', 'name' => $greekStringConversion->grstrtoupper('Βασκιρικά')),
                array('code' => 'bar', 'name' => $greekStringConversion->grstrtoupper('Βαυαρικά')),
                array('code' => 'bn', 'name' => $greekStringConversion->grstrtoupper('Βεγκαλικά')),
                array('code' => 'vec', 'name' => $greekStringConversion->grstrtoupper('Βενετικά')),
                array('code' => 've', 'name' => $greekStringConversion->grstrtoupper('Βέντα')),
                array('code' => 'vi', 'name' => $greekStringConversion->grstrtoupper('Βιετναμικά')),
                array('code' => 'my', 'name' => $greekStringConversion->grstrtoupper('Βιρμανικά')),
                array('code' => 'bi', 'name' => $greekStringConversion->grstrtoupper('Βισλαμικά')),
                array('code' => 'bh', 'name' => $greekStringConversion->grstrtoupper('Βιχαρικά')),
                array('code' => 'nd', 'name' => $greekStringConversion->grstrtoupper('Βοερειο-νδεβελικά')),
                array('code' => 'vo', 'name' => $greekStringConversion->grstrtoupper('Βολαπούκ')),
                array('code' => 'sme', 'name' => $greekStringConversion->grstrtoupper('Βορειο-Σαμικά')),
                array('code' => 'bs', 'name' => $greekStringConversion->grstrtoupper('Βοσνιακά')),
                array('code' => 'pcc', 'name' => $greekStringConversion->grstrtoupper('Βουϊεϊκά')),
                array('code' => 'bg', 'name' => $greekStringConversion->grstrtoupper('Βουλγάρικα')),
                array('code' => 'br', 'name' => $greekStringConversion->grstrtoupper('Βρετονικά')),
                array('code' => 'fr', 'name' => $greekStringConversion->grstrtoupper('Γαλλικά')),
                array('code' => 'frp', 'name' => $greekStringConversion->grstrtoupper('Γαλλο-Προβηγκιακά')),
                array('code' => 'de', 'name' => $greekStringConversion->grstrtoupper('Γερμανικά')),
                array('code' => 'ka', 'name' => $greekStringConversion->grstrtoupper('Γεωργιανά')),
                array('code' => 'yi', 'name' => $greekStringConversion->grstrtoupper('Γίντις')),
                array('code' => 'yo', 'name' => $greekStringConversion->grstrtoupper('Γιορούμπα')),
                array('code' => 'esu', 'name' => $greekStringConversion->grstrtoupper('Γιουπικά')),
                array('code' => 'guz', 'name' => $greekStringConversion->grstrtoupper('Γουσιϊκά')),
                array('code' => 'dag', 'name' => $greekStringConversion->grstrtoupper('Δαγβανικά')),
                array('code' => 'da', 'name' => $greekStringConversion->grstrtoupper('Δανικά')),
                array('code' => 'he', 'name' => $greekStringConversion->grstrtoupper('Εβραϊκά')),
                array('code' => 'gsw', 'name' => $greekStringConversion->grstrtoupper('Ελβετικά Γερμανικά')),
                array('code' => 'el', 'name' => $greekStringConversion->grstrtoupper('Ελληνικά')),
                array('code' => 'egl', 'name' => $greekStringConversion->grstrtoupper('Εμιλιακά')),
                array('code' => 'myv', 'name' => $greekStringConversion->grstrtoupper('Ερριακά')),
                array('code' => 'et', 'name' => $greekStringConversion->grstrtoupper('Εσθονικά')),
                array('code' => 'eo', 'name' => $greekStringConversion->grstrtoupper('Εσπεράντο')),
                array('code' => 'zza', 'name' => $greekStringConversion->grstrtoupper('Ζαζαϊκά')),
                array('code' => 'za', 'name' => $greekStringConversion->grstrtoupper('Ζουάνγκ')),
                array('code' => 'zu', 'name' => $greekStringConversion->grstrtoupper('Ζουλού')),
                array('code' => 'bo', 'name' => $greekStringConversion->grstrtoupper('Θιβετιανά')),
                array('code' => 'jv', 'name' => $greekStringConversion->grstrtoupper('Ιαβανικά')),
                array('code' => 'ja', 'name' => $greekStringConversion->grstrtoupper('Ιαπωνικά')),
                array('code' => 'ig', 'name' => $greekStringConversion->grstrtoupper('Ίγβο')),
                array('code' => 'ibd', 'name' => $greekStringConversion->grstrtoupper('Ιγουάγια')),
                array('code' => 'yey', 'name' => $greekStringConversion->grstrtoupper('Ιεγικά')),
                array('code' => 'inh', 'name' => $greekStringConversion->grstrtoupper('Ινγουσικά')),
                array('code' => 'hi', 'name' => $greekStringConversion->grstrtoupper('Ινδικά')),
                array('code' => 'ind', 'name' => $greekStringConversion->grstrtoupper('Ινδονησιακά')),
                array('code' => 'iu', 'name' => $greekStringConversion->grstrtoupper('Ινούκτιτουτ')),
                array('code' => 'ik', 'name' => $greekStringConversion->grstrtoupper('Ινουπιακά')),
                array('code' => 'ia', 'name' => $greekStringConversion->grstrtoupper('Ιντερλίνγκουα')),
                array('code' => 'ga', 'name' => $greekStringConversion->grstrtoupper('Ιρλανδικά')),
                array('code' => 'is', 'name' => $greekStringConversion->grstrtoupper('Ισλανδικά')),
                array('code' => 'es', 'name' => $greekStringConversion->grstrtoupper('Ισπανικά')),
                array('code' => 'lad', 'name' => $greekStringConversion->grstrtoupper('Ισπανοεβραϊκά')),
                array('code' => 'it', 'name' => $greekStringConversion->grstrtoupper('Ιταλικά')),
                array('code' => 'kbd', 'name' => $greekStringConversion->grstrtoupper('Καβαρδικά')),
                array('code' => 'kk', 'name' => $greekStringConversion->grstrtoupper('Καζακικά')),
                array('code' => 'kl', 'name' => $greekStringConversion->grstrtoupper('Καλαλισουτικά')),
                array('code' => 'xal', 'name' => $greekStringConversion->grstrtoupper('Καλμύκ')),
                array('code' => 'sro', 'name' => $greekStringConversion->grstrtoupper('Καμπιδανικά')),
                array('code' => 'kab', 'name' => $greekStringConversion->grstrtoupper('Κάμπυλε')),
                array('code' => 'kn', 'name' => $greekStringConversion->grstrtoupper('Κανναδικά')),
                array('code' => 'kr', 'name' => $greekStringConversion->grstrtoupper('Κανοθρικά')),
                array('code' => 'yue', 'name' => $greekStringConversion->grstrtoupper('Καντονικά')),
                array('code' => 'ks', 'name' => $greekStringConversion->grstrtoupper('Κασμιρικά')),
                array('code' => 'csb', 'name' => $greekStringConversion->grstrtoupper('Κασουβιανικά')),
                array('code' => 'ca', 'name' => $greekStringConversion->grstrtoupper('Καταλονικά')),
                array('code' => 'zpf', 'name' => $greekStringConversion->grstrtoupper('Κβιατόνι Ζαποτέκ')),
                array('code' => 'rw', 'name' => $greekStringConversion->grstrtoupper('Κενιο-ρουαντικά')),
                array('code' => 'bcl', 'name' => $greekStringConversion->grstrtoupper('Κεντρο-Βικολανικά')),
                array('code' => 'qu', 'name' => $greekStringConversion->grstrtoupper('Κετσβανικά')),
                array('code' => 'ki', 'name' => $greekStringConversion->grstrtoupper('Κικούγιου')),
                array('code' => 'kmb', 'name' => $greekStringConversion->grstrtoupper('Κιμβούντου')),
                array('code' => 'zh', 'name' => $greekStringConversion->grstrtoupper('Κινεζικά')),
                array('code' => 'cjy', 'name' => $greekStringConversion->grstrtoupper('Κινέζικα Jin')),
                array('code' => 'wuu', 'name' => $greekStringConversion->grstrtoupper('Κινέζικα Βού')),
                array('code' => 'hsn', 'name' => $greekStringConversion->grstrtoupper('Κινέζικα Κιάνκ')),
                array('code' => 'gan', 'name' => $greekStringConversion->grstrtoupper('Κινεζική Γκαν')),
                array('code' => 'rn', 'name' => $greekStringConversion->grstrtoupper('Κιρουνδικά')),
                array('code' => 'tlh', 'name' => $greekStringConversion->grstrtoupper('Κλίγκον')),
                array('code' => 'kv', 'name' => $greekStringConversion->grstrtoupper('Κομικά')),
                array('code' => 'kg', 'name' => $greekStringConversion->grstrtoupper('Κονγκολικά')),
                array('code' => 'gom', 'name' => $greekStringConversion->grstrtoupper('Κονκανί')),
                array('code' => 'ko', 'name' => $greekStringConversion->grstrtoupper('Κορεατικά')),
                array('code' => 'kw', 'name' => $greekStringConversion->grstrtoupper('Κορνουαλικά')),
                array('code' => 'co', 'name' => $greekStringConversion->grstrtoupper('Κορσικανικά')),
                array('code' => 'avk', 'name' => $greekStringConversion->grstrtoupper('Κοτάβα')),
                array('code' => 'kj', 'name' => $greekStringConversion->grstrtoupper('Κουανιάμα')),
                array('code' => 'ku', 'name' => $greekStringConversion->grstrtoupper('Κουρδικά')),
                array('code' => 'kmr', 'name' => $greekStringConversion->grstrtoupper('Κουρμαντζικά')),
                array('code' => 'kfr', 'name' => $greekStringConversion->grstrtoupper('Κούτσι')),
                array('code' => 'kea', 'name' => $greekStringConversion->grstrtoupper('Κρεολικά Πρασίνου Ακρωτηρίου')),
                array('code' => 'lou', 'name' => $greekStringConversion->grstrtoupper('Κρεολική της Λουιζιάνα')),
                array('code' => 'cr', 'name' => $greekStringConversion->grstrtoupper('Κρηϊκά')),
                array('code' => 'mus', 'name' => $greekStringConversion->grstrtoupper('Κρηκικά')),
                array('code' => 'kri', 'name' => $greekStringConversion->grstrtoupper('Κριολικά')),
                array('code' => 'hr', 'name' => $greekStringConversion->grstrtoupper('Κροατικά')),
                array('code' => 'ky', 'name' => $greekStringConversion->grstrtoupper('Κυργυζικά')),
                array('code' => 'lzz', 'name' => $greekStringConversion->grstrtoupper('Λαζ')),
                array('code' => 'lbe', 'name' => $greekStringConversion->grstrtoupper('Λάκ')),
                array('code' => 'lkt', 'name' => $greekStringConversion->grstrtoupper('Λακότα')),
                array('code' => 'lo', 'name' => $greekStringConversion->grstrtoupper('Λαοϊκά')),
                array('code' => 'ltg', 'name' => $greekStringConversion->grstrtoupper('Λατγαλικά')),
                array('code' => 'la', 'name' => $greekStringConversion->grstrtoupper('Λατινικά')),
                array('code' => 'lez', 'name' => $greekStringConversion->grstrtoupper('Λεζγικά')),
                array('code' => 'lv', 'name' => $greekStringConversion->grstrtoupper('Λετονικά')),
                array('code' => 'be', 'name' => $greekStringConversion->grstrtoupper('Λευκορωσικά')),
                array('code' => 'lij', 'name' => $greekStringConversion->grstrtoupper('Λιγουρικά')),
                array('code' => 'lt', 'name' => $greekStringConversion->grstrtoupper('Λιθουανικά')),
                array('code' => 'li', 'name' => $greekStringConversion->grstrtoupper('Λιμβουργικά')),
                array('code' => 'loz', 'name' => $greekStringConversion->grstrtoupper('Λόζι')),
                array('code' => 'ilo', 'name' => $greekStringConversion->grstrtoupper('Λόκο')),
                array('code' => 'lmo', 'name' => $greekStringConversion->grstrtoupper('Λομβαρδικά')),
                array('code' => 'lb', 'name' => $greekStringConversion->grstrtoupper('Λουξεμβουργικά')),
                array('code' => 'lrc', 'name' => $greekStringConversion->grstrtoupper('Λουρικά')),
                array('code' => 'mg', 'name' => $greekStringConversion->grstrtoupper('Μαδαγασκαρικά')),
                array('code' => 'mzn', 'name' => $greekStringConversion->grstrtoupper('Μαζανδαρανικά')),
                array('code' => 'vmf', 'name' => $greekStringConversion->grstrtoupper('Μαινοφρανκικά')),
                array('code' => 'ml', 'name' => $greekStringConversion->grstrtoupper('Μαλαϊαλαμικά')),
                array('code' => 'ms', 'name' => $greekStringConversion->grstrtoupper('Μαλαισιακά')),
                array('code' => 'mt', 'name' => $greekStringConversion->grstrtoupper('Μαλταϊκά')),
                array('code' => 'gv', 'name' => $greekStringConversion->grstrtoupper('Μανξ')),
                array('code' => 'mnc', 'name' => $greekStringConversion->grstrtoupper('Μανσουχικά')),
                array('code' => 'arn', 'name' => $greekStringConversion->grstrtoupper('Μαπουδουγκούν')),
                array('code' => 'mr', 'name' => $greekStringConversion->grstrtoupper('Μαρατικά')),
                array('code' => 'chm', 'name' => $greekStringConversion->grstrtoupper('Μαρί')),
                array('code' => 'mh', 'name' => $greekStringConversion->grstrtoupper('Μαρσαλικά')),
                array('code' => 'msb', 'name' => $greekStringConversion->grstrtoupper('Μασμπατένιο')),
                array('code' => 'mi', 'name' => $greekStringConversion->grstrtoupper('Μαωρικά')),
                array('code' => 'pdt', 'name' => $greekStringConversion->grstrtoupper('Μεννονιτικά Κ.Γερμανίας')),
                array('code' => 'apm', 'name' => $greekStringConversion->grstrtoupper('Μεσκαλικά-Χιρικαϊκά')),
                array('code' => 'mic', 'name' => $greekStringConversion->grstrtoupper('Μικμάκ')),
                array('code' => 'nan', 'name' => $greekStringConversion->grstrtoupper('Μιν Ναν')),
                array('code' => 'min', 'name' => $greekStringConversion->grstrtoupper('Μινανγκαμπάου')),
                array('code' => 'mn', 'name' => $greekStringConversion->grstrtoupper('Μογγολικά')),
                array('code' => 'mdf', 'name' => $greekStringConversion->grstrtoupper('Μοξικά')),
                array('code' => 'new', 'name' => $greekStringConversion->grstrtoupper('Μπάσα Νεπάλ')),
                array('code' => 'bsk', 'name' => $greekStringConversion->grstrtoupper('Μπουρουσάσκι')),
                array('code' => 'bzd', 'name' => $greekStringConversion->grstrtoupper('Μπρι-μπρι')),
                array('code' => 'moh', 'name' => $greekStringConversion->grstrtoupper('Μώχωκ')),
                array('code' => 'nv', 'name' => $greekStringConversion->grstrtoupper('Ναβαχικά')),
                array('code' => 'nah', 'name' => $greekStringConversion->grstrtoupper('Ναουάτλ')),
                array('code' => 'na', 'name' => $greekStringConversion->grstrtoupper('Ναουρουϊκά')),
                array('code' => 'nap', 'name' => $greekStringConversion->grstrtoupper('Ναπολιτανικά')),
                array('code' => 'nsk', 'name' => $greekStringConversion->grstrtoupper('Νασκαπικά')),
                array('code' => 'ng', 'name' => $greekStringConversion->grstrtoupper('Νδονγικά')),
                array('code' => 'ne', 'name' => $greekStringConversion->grstrtoupper('Νεπαλικά')),
                array('code' => 'nog', 'name' => $greekStringConversion->grstrtoupper('Νογκάι')),
                array('code' => 'no', 'name' => $greekStringConversion->grstrtoupper('Νορβηγικά Bokmål')),
                array('code' => 'nn', 'name' => $greekStringConversion->grstrtoupper('Νορβηγικά Nynorsk')),
                array('code' => 'nr', 'name' => $greekStringConversion->grstrtoupper('Νοτιο-νδεβελικά')),
                array('code' => 'ii', 'name' => $greekStringConversion->grstrtoupper('Νουόσου')),
                array('code' => 'prs', 'name' => $greekStringConversion->grstrtoupper('Ντάρι')),
                array('code' => 'dz', 'name' => $greekStringConversion->grstrtoupper('Ντζόνγκα')),
                array('code' => 'dv', 'name' => $greekStringConversion->grstrtoupper('Ντιβέχι')),
                array('code' => 'din', 'name' => $greekStringConversion->grstrtoupper('Ντίνκα')),
                array('code' => 'ota', 'name' => $greekStringConversion->grstrtoupper('Οθωμανικά τουρκικά')),
                array('code' => 'ryu', 'name' => $greekStringConversion->grstrtoupper('Οκινάουα')),
                array('code' => 'nl', 'name' => $greekStringConversion->grstrtoupper('Ολλανδικά')),
                array('code' => 'oc', 'name' => $greekStringConversion->grstrtoupper('Οξιτανικά')),
                array('code' => 'osa', 'name' => $greekStringConversion->grstrtoupper('Οσάγκε')),
                array('code' => 'os', 'name' => $greekStringConversion->grstrtoupper('Οσσετικά')),
                array('code' => 'cy', 'name' => $greekStringConversion->grstrtoupper('Ουαλικά')),
                array('code' => 'hu', 'name' => $greekStringConversion->grstrtoupper('Ουγγρικά')),
                array('code' => 'udm', 'name' => $greekStringConversion->grstrtoupper('Ουδμουρτικά')),
                array('code' => 'uz', 'name' => $greekStringConversion->grstrtoupper('Ουζμπεκικά')),
                array('code' => 'ug', 'name' => $greekStringConversion->grstrtoupper('Ουιγουρικά')),
                array('code' => 'uk', 'name' => $greekStringConversion->grstrtoupper('Ουκρανικά')),
                array('code' => 'wo', 'name' => $greekStringConversion->grstrtoupper('Ουολοφικά')),
                array('code' => 'ur', 'name' => $greekStringConversion->grstrtoupper('Ουρντού')),
                array('code' => 'pau', 'name' => $greekStringConversion->grstrtoupper('Παλαυανικά')),
                array('code' => 'pln', 'name' => $greekStringConversion->grstrtoupper('Παλενκικά')),
                array('code' => 'pi', 'name' => $greekStringConversion->grstrtoupper('Παλικά')),
                array('code' => 'pag', 'name' => $greekStringConversion->grstrtoupper('Πανγκασικά')),
                array('code' => 'pap', 'name' => $greekStringConversion->grstrtoupper('Παπιαμέντο')),
                array('code' => 'ps', 'name' => $greekStringConversion->grstrtoupper('Παστουνικά')),
                array('code' => 'pms', 'name' => $greekStringConversion->grstrtoupper('Πεδεμοντικά')),
                array('code' => 'fa', 'name' => $greekStringConversion->grstrtoupper('Περσικά')),
                array('code' => 'pcd', 'name' => $greekStringConversion->grstrtoupper('Πικαρδικά')),
                array('code' => 'pl', 'name' => $greekStringConversion->grstrtoupper('Πολωνικά')),
                array('code' => 'pt', 'name' => $greekStringConversion->grstrtoupper('Πορτογαλικά')),
                array('code' => 'fuc', 'name' => $greekStringConversion->grstrtoupper('Πούλαρ')),
                array('code' => 'rap', 'name' => $greekStringConversion->grstrtoupper('Ραπα-Νούι')),
                array('code' => 'rhg', 'name' => $greekStringConversion->grstrtoupper('Ροϊγκιακά')),
                array('code' => 'rom', 'name' => $greekStringConversion->grstrtoupper('Ρόμα')),
                array('code' => 'cgg', 'name' => $greekStringConversion->grstrtoupper('Ρουκίγκα')),
                array('code' => 'ro', 'name' => $greekStringConversion->grstrtoupper('Ρουμάνικα')),
                array('code' => 'rue', 'name' => $greekStringConversion->grstrtoupper('Ρούσιν')),
                array('code' => 'ru', 'name' => $greekStringConversion->grstrtoupper('Ρώσσικα')),
                array('code' => 'sm', 'name' => $greekStringConversion->grstrtoupper('Σαμοαϊκά')),
                array('code' => 'sg', 'name' => $greekStringConversion->grstrtoupper('Σανγικά')),
                array('code' => 'sa', 'name' => $greekStringConversion->grstrtoupper('Σανσκριτικά')),
                array('code' => 'sc', 'name' => $greekStringConversion->grstrtoupper('Σαρδηνικά')),
                array('code' => 'ceb', 'name' => $greekStringConversion->grstrtoupper('Σεμπουάνο')),
                array('code' => 'sr', 'name' => $greekStringConversion->grstrtoupper('Σερβικά')),
                array('code' => 'srr', 'name' => $greekStringConversion->grstrtoupper('Σερέρ')),
                array('code' => 'trv', 'name' => $greekStringConversion->grstrtoupper('Σηδικά')),
                array('code' => 'scn', 'name' => $greekStringConversion->grstrtoupper('Σικελικά')),
                array('code' => 'si', 'name' => $greekStringConversion->grstrtoupper('Σιναλικά')),
                array('code' => 'sd', 'name' => $greekStringConversion->grstrtoupper('Σινδικά')),
                array('code' => 'sco', 'name' => $greekStringConversion->grstrtoupper('Σκωττικά')),
                array('code' => 'mk', 'name' => $greekStringConversion->grstrtoupper('Σλαβομακεδονικά')),
                array('code' => 'sk', 'name' => $greekStringConversion->grstrtoupper('Σλοβακικά')),
                array('code' => 'sl', 'name' => $greekStringConversion->grstrtoupper('Σλοβενικά')),
                array('code' => 'so', 'name' => $greekStringConversion->grstrtoupper('Σομαλικά')),
                array('code' => 'sn', 'name' => $greekStringConversion->grstrtoupper('Σονικά')),
                array('code' => 'st', 'name' => $greekStringConversion->grstrtoupper('Σότο')),
                array('code' => 'sw', 'name' => $greekStringConversion->grstrtoupper('Σουαχίλι')),
                array('code' => 'swg', 'name' => $greekStringConversion->grstrtoupper('Σουηβικά Γερμανικά')),
                array('code' => 'sv', 'name' => $greekStringConversion->grstrtoupper('Σουηδικά')),
                array('code' => 'su', 'name' => $greekStringConversion->grstrtoupper('Σουνδανικά')),
                array('code' => 'syl', 'name' => $greekStringConversion->grstrtoupper('Συλετικά')),
                array('code' => 'ss', 'name' => $greekStringConversion->grstrtoupper('Σωατικά')),
                array('code' => 'tl', 'name' => $greekStringConversion->grstrtoupper('Ταγκαλόγκ')),
                array('code' => 'th', 'name' => $greekStringConversion->grstrtoupper('Ταϊλανδικά')),
                array('code' => 'ty', 'name' => $greekStringConversion->grstrtoupper('Ταϊτιανά')),
                array('code' => 'tzm', 'name' => $greekStringConversion->grstrtoupper('Ταμαζική Κεντρικού Άτλαντος')),
                array('code' => 'ta', 'name' => $greekStringConversion->grstrtoupper('Ταμίλ')),
                array('code' => 'tmh', 'name' => $greekStringConversion->grstrtoupper('Ταργική')),
                array('code' => 'tt', 'name' => $greekStringConversion->grstrtoupper('Ταταρικά')),
                array('code' => 'crh', 'name' => $greekStringConversion->grstrtoupper('Ταταρικά Κριμαίας')),
                array('code' => 'tg', 'name' => $greekStringConversion->grstrtoupper('Τατζικικά')),
                array('code' => 'te', 'name' => $greekStringConversion->grstrtoupper('Τελούγκου')),
                array('code' => 'tet', 'name' => $greekStringConversion->grstrtoupper('Τέτουμ')),
                array('code' => 'ti', 'name' => $greekStringConversion->grstrtoupper('Τιγρινικά')),
                array('code' => 'tli', 'name' => $greekStringConversion->grstrtoupper('Τλινγκιτ')),
                array('code' => 'jam', 'name' => $greekStringConversion->grstrtoupper('Τξαμαικανά Πατουά')),
                array('code' => 'to', 'name' => $greekStringConversion->grstrtoupper('Τογκικά')),
                array('code' => 'tpi', 'name' => $greekStringConversion->grstrtoupper('Τοκ Πισίν')),
                array('code' => 'x', 'name' => $greekStringConversion->grstrtoupper('Τόκι Πόνα')),
                array('code' => 'srn', 'name' => $greekStringConversion->grstrtoupper('Τονγκο-Σρανανικά')),
                array('code' => 'tdn', 'name' => $greekStringConversion->grstrtoupper('Τοντάνο')),
                array('code' => 'tw', 'name' => $greekStringConversion->grstrtoupper('Τούι')),
                array('code' => 'tr', 'name' => $greekStringConversion->grstrtoupper('Τουρκικά')),
                array('code' => 'tk', 'name' => $greekStringConversion->grstrtoupper('Τουρκμενικά')),
                array('code' => 'tus', 'name' => $greekStringConversion->grstrtoupper('Τουσκαρόρα')),
                array('code' => 'tn', 'name' => $greekStringConversion->grstrtoupper('Τσβάνα')),
                array('code' => 'chr', 'name' => $greekStringConversion->grstrtoupper('Τσεροκικά')),
                array('code' => 'ce', 'name' => $greekStringConversion->grstrtoupper('Τσετσένικα')),
                array('code' => 'cs', 'name' => $greekStringConversion->grstrtoupper('Τσεχικά')),
                array('code' => 'ny', 'name' => $greekStringConversion->grstrtoupper('Τσιτσεβαχικά')),
                array('code' => 'ts', 'name' => $greekStringConversion->grstrtoupper('Τσονγκικά')),
                array('code' => 'cv', 'name' => $greekStringConversion->grstrtoupper('Τσουβασικά')),
                array('code' => 'yua', 'name' => $greekStringConversion->grstrtoupper('Υουκατικά Μάγια')),
                array('code' => 'fi', 'name' => $greekStringConversion->grstrtoupper('Φινλανδικά')),
                array('code' => 'vls', 'name' => $greekStringConversion->grstrtoupper('Φλαμανδικά')),
                array('code' => 'ff', 'name' => $greekStringConversion->grstrtoupper('Φουλαϊκά')),
                array('code' => 'fur', 'name' => $greekStringConversion->grstrtoupper('Φριουλικά')),
                array('code' => 'haw', 'name' => $greekStringConversion->grstrtoupper('Χαβαϊκά')),
                array('code' => 'hak', 'name' => $greekStringConversion->grstrtoupper('Χάκκα')),
                array('code' => 'ch', 'name' => $greekStringConversion->grstrtoupper('Χαμορρικά')),
                array('code' => 'kca', 'name' => $greekStringConversion->grstrtoupper('Χαντικά')),
                array('code' => 'ha', 'name' => $greekStringConversion->grstrtoupper('Χάουσα')),
                array('code' => 'hz', 'name' => $greekStringConversion->grstrtoupper('Χερερικά')),
                array('code' => 'ho', 'name' => $greekStringConversion->grstrtoupper('Χίρι μότου')),
                array('code' => 'km', 'name' => $greekStringConversion->grstrtoupper('Χμερικά')),
                array('code' => 'hmn', 'name' => $greekStringConversion->grstrtoupper('Χμονγκ')),
                array('code' => 'xh', 'name' => $greekStringConversion->grstrtoupper('Χόζα')),
            )
        );

        \DB::table('language_levels')->insert(
            array(
                array('description'   => 'Επιλέξτε επίπεδο'),
                array('description'   => 'Χαμηλό'),
                array('description'   => 'Μέτριο'),
                array('description'   => 'Καλό'),
                array('description'   => 'Πολύ Καλό'),
                array('description'   => 'Άριστο'),
            )
        );
    }
}
