<?php

use Illuminate\Database\Seeder;


class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('languages')->insert(
            array(
                array('code' => '---', 'name' => 'Επιλέξτε γλώσσα'),
                array('code' => 'abq', 'name' => 'Αβαζικά'),
                array('code' => 'av', 'name' => 'Αβαρικά'),
                array('code' => 'en', 'name' => 'Αγγλικά'),
                array('code' => 'ady', 'name' => 'Αδυγικά'),
                array('code' => 'az', 'name' => 'Αζερικά'),
                array('code' => 'ht', 'name' => 'Αϊτικά'),
                array('code' => 'ak', 'name' => 'Άκαν'),
                array('code' => 'sq', 'name' => 'Αλβανικά'),
                array('code' => 'ale', 'name' => 'Αλεουτικά'),
                array('code' => 'am', 'name' => 'Αμαρικά'),
                array('code' => 'ab', 'name' => 'Αμπχαζικά'),
                array('code' => 'hsb', 'name' => 'Άνω Σορβικά'),
                array('code' => 'ar', 'name' => 'Αραβικά'),
                array('code' => 'an', 'name' => 'Αραγονικά'),
                array('code' => 'hy', 'name' => 'Αρμένικα'),
                array('code' => 'aae', 'name' => 'Αρμπερές'),
                array('code' => 'grc', 'name' => 'Ἀρχαῖα Ἑλληνικά'),
                array('code' => 'as', 'name' => 'Ασαμικά'),
                array('code' => 'mey', 'name' => 'Ασσανικά'),
                array('code' => 'ast', 'name' => 'Αστουρικά'),
                array('code' => 'ay', 'name' => 'Αϋμαρικά'),
                array('code' => 'aa', 'name' => 'Αφάρ'),
                array('code' => 'af', 'name' => 'Αφρικανικά'),
                array('code' => 'wa', 'name' => 'Βαλλονικά'),
                array('code' => 'bal', 'name' => 'Βαλουχικά'),
                array('code' => 'bm', 'name' => 'Βαμβαρικά'),
                array('code' => 'bcj', 'name' => 'Βαρδικά'),
                array('code' => 'eu', 'name' => 'Βασκικά'),
                array('code' => 'ba', 'name' => 'Βασκιρικά'),
                array('code' => 'bar', 'name' => 'Βαυαρικά'),
                array('code' => 'bn', 'name' => 'Βεγκαλικά'),
                array('code' => 'vec', 'name' => 'Βενετικά'),
                array('code' => 've', 'name' => 'Βέντα'),
                array('code' => 'vi', 'name' => 'Βιετναμικά'),
                array('code' => 'my', 'name' => 'Βιρμανικά'),
                array('code' => 'bi', 'name' => 'Βισλαμικά'),
                array('code' => 'bh', 'name' => 'Βιχαρικά'),
                array('code' => 'nd', 'name' => 'Βοερειο-νδεβελικά'),
                array('code' => 'vo', 'name' => 'Βολαπούκ'),
                array('code' => 'sme', 'name' => 'Βορειο-Σαμικά'),
                array('code' => 'bs', 'name' => 'Βοσνιακά'),
                array('code' => 'pcc', 'name' => 'Βουϊεϊκά'),
                array('code' => 'bg', 'name' => 'Βουλγάρικα'),
                array('code' => 'br', 'name' => 'Βρετονικά'),
                array('code' => 'fr', 'name' => 'Γαλλικά'),
                array('code' => 'frp', 'name' => 'Γαλλο-Προβηγκιακά'),
                array('code' => 'de', 'name' => 'Γερμανικά'),
                array('code' => 'ka', 'name' => 'Γεωργιανά'),
                array('code' => 'yi', 'name' => 'Γίντις'),
                array('code' => 'yo', 'name' => 'Γιορούμπα'),
                array('code' => 'esu', 'name' => 'Γιουπικά'),
                array('code' => 'guz', 'name' => 'Γουσιϊκά'),
                array('code' => 'dag', 'name' => 'Δαγβανικά'),
                array('code' => 'da', 'name' => 'Δανικά'),
                array('code' => 'he', 'name' => 'Εβραϊκά'),
                array('code' => 'gsw', 'name' => 'Ελβετικά Γερμανικά'),
                array('code' => 'el', 'name' => 'Ελληνικά'),
                array('code' => 'egl', 'name' => 'Εμιλιακά'),
                array('code' => 'myv', 'name' => 'Ερριακά'),
                array('code' => 'et', 'name' => 'Εσθονικά'),
                array('code' => 'eo', 'name' => 'Εσπεράντο'),
                array('code' => 'zza', 'name' => 'Ζαζαϊκά'),
                array('code' => 'za', 'name' => 'Ζουάνγκ'),
                array('code' => 'zu', 'name' => 'Ζουλού'),
                array('code' => 'bo', 'name' => 'Θιβετιανά'),
                array('code' => 'jv', 'name' => 'Ιαβανικά'),
                array('code' => 'ja', 'name' => 'Ιαπωνικά'),
                array('code' => 'ig', 'name' => 'Ίγβο'),
                array('code' => 'ibd', 'name' => 'Ιγουάγια'),
                array('code' => 'yey', 'name' => 'Ιεγικά'),
                array('code' => 'inh', 'name' => 'Ινγουσικά'),
                array('code' => 'hi', 'name' => 'Ινδικά'),
                array('code' => 'ind', 'name' => 'Ινδονησιακά'),
                array('code' => 'iu', 'name' => 'Ινούκτιτουτ'),
                array('code' => 'ik', 'name' => 'Ινουπιακά'),
                array('code' => 'ia', 'name' => 'Ιντερλίνγκουα'),
                array('code' => 'ga', 'name' => 'Ιρλανδικά'),
                array('code' => 'is', 'name' => 'Ισλανδικά'),
                array('code' => 'es', 'name' => 'Ισπανικά'),
                array('code' => 'lad', 'name' => 'Ισπανοεβραϊκά'),
                array('code' => 'it', 'name' => 'Ιταλικά'),
                array('code' => 'kbd', 'name' => 'Καβαρδικά'),
                array('code' => 'kk', 'name' => 'Καζακικά'),
                array('code' => 'kl', 'name' => 'Καλαλισουτικά'),
                array('code' => 'xal', 'name' => 'Καλμύκ'),
                array('code' => 'sro', 'name' => 'Καμπιδανικά'),
                array('code' => 'kab', 'name' => 'Κάμπυλε'),
                array('code' => 'kn', 'name' => 'Κανναδικά'),
                array('code' => 'kr', 'name' => 'Κανοθρικά'),
                array('code' => 'yue', 'name' => 'Καντονικά'),
                array('code' => 'ks', 'name' => 'Κασμιρικά'),
                array('code' => 'csb', 'name' => 'Κασουβιανικά'),
                array('code' => 'ca', 'name' => 'Καταλονικά'),
                array('code' => 'zpf', 'name' => 'Κβιατόνι Ζαποτέκ'),
                array('code' => 'rw', 'name' => 'Κενιο-ρουαντικά'),
                array('code' => 'bcl', 'name' => 'Κεντρο-Βικολανικά'),
                array('code' => 'qu', 'name' => 'Κετσβανικά'),
                array('code' => 'ki', 'name' => 'Κικούγιου'),
                array('code' => 'kmb', 'name' => 'Κιμβούντου'),
                array('code' => 'zh', 'name' => 'Κινεζικά'),
                array('code' => 'cjy', 'name' => 'Κινέζικα Jin'),
                array('code' => 'wuu', 'name' => 'Κινέζικα Βού'),
                array('code' => 'hsn', 'name' => 'Κινέζικα Κιάνκ'),
                array('code' => 'gan', 'name' => 'Κινεζική Γκαν'),
                array('code' => 'rn', 'name' => 'Κιρουνδικά'),
                array('code' => 'tlh', 'name' => 'Κλίγκον'),
                array('code' => 'kv', 'name' => 'Κομικά'),
                array('code' => 'kg', 'name' => 'Κονγκολικά'),
                array('code' => 'gom', 'name' => 'Κονκανί'),
                array('code' => 'ko', 'name' => 'Κορεατικά'),
                array('code' => 'kw', 'name' => 'Κορνουαλικά'),
                array('code' => 'co', 'name' => 'Κορσικανικά'),
                array('code' => 'avk', 'name' => 'Κοτάβα'),
                array('code' => 'kj', 'name' => 'Κουανιάμα'),
                array('code' => 'ku', 'name' => 'Κουρδικά'),
                array('code' => 'kmr', 'name' => 'Κουρμαντζικά'),
                array('code' => 'kfr', 'name' => 'Κούτσι'),
                array('code' => 'kea', 'name' => 'Κρεολικά Πρασίνου Ακρωτηρίου'),
                array('code' => 'lou', 'name' => 'Κρεολική της Λουιζιάνα'),
                array('code' => 'cr', 'name' => 'Κρηϊκά'),
                array('code' => 'mus', 'name' => 'Κρηκικά'),
                array('code' => 'kri', 'name' => 'Κριολικά'),
                array('code' => 'hr', 'name' => 'Κροατικά'),
                array('code' => 'ky', 'name' => 'Κυργυζικά'),
                array('code' => 'lzz', 'name' => 'Λαζ'),
                array('code' => 'lbe', 'name' => 'Λάκ'),
                array('code' => 'lkt', 'name' => 'Λακότα'),
                array('code' => 'lo', 'name' => 'Λαοϊκά'),
                array('code' => 'ltg', 'name' => 'Λατγαλικά'),
                array('code' => 'la', 'name' => 'Λατινικά'),
                array('code' => 'lez', 'name' => 'Λεζγικά'),
                array('code' => 'lv', 'name' => 'Λετονικά'),
                array('code' => 'be', 'name' => 'Λευκορωσικά'),
                array('code' => 'lij', 'name' => 'Λιγουρικά'),
                array('code' => 'lt', 'name' => 'Λιθουανικά'),
                array('code' => 'li', 'name' => 'Λιμβουργικά'),
                array('code' => 'loz', 'name' => 'Λόζι'),
                array('code' => 'ilo', 'name' => 'Λόκο'),
                array('code' => 'lmo', 'name' => 'Λομβαρδικά'),
                array('code' => 'lb', 'name' => 'Λουξεμβουργικά'),
                array('code' => 'lrc', 'name' => 'Λουρικά'),
                array('code' => 'mg', 'name' => 'Μαδαγασκαρικά'),
                array('code' => 'mzn', 'name' => 'Μαζανδαρανικά'),
                array('code' => 'vmf', 'name' => 'Μαινοφρανκικά'),
                array('code' => 'ml', 'name' => 'Μαλαϊαλαμικά'),
                array('code' => 'ms', 'name' => 'Μαλαισιακά'),
                array('code' => 'mt', 'name' => 'Μαλταϊκά'),
                array('code' => 'gv', 'name' => 'Μανξ'),
                array('code' => 'mnc', 'name' => 'Μανσουχικά'),
                array('code' => 'arn', 'name' => 'Μαπουδουγκούν'),
                array('code' => 'mr', 'name' => 'Μαρατικά'),
                array('code' => 'chm', 'name' => 'Μαρί'),
                array('code' => 'mh', 'name' => 'Μαρσαλικά'),
                array('code' => 'msb', 'name' => 'Μασμπατένιο'),
                array('code' => 'mi', 'name' => 'Μαωρικά'),
                array('code' => 'pdt', 'name' => 'Μεννονιτικά Κ.Γερμανίας'),
                array('code' => 'apm', 'name' => 'Μεσκαλικά-Χιρικαϊκά'),
                array('code' => 'mic', 'name' => 'Μικμάκ'),
                array('code' => 'nan', 'name' => 'Μιν Ναν'),
                array('code' => 'min', 'name' => 'Μινανγκαμπάου'),
                array('code' => 'mn', 'name' => 'Μογγολικά'),
                array('code' => 'mdf', 'name' => 'Μοξικά'),
                array('code' => 'new', 'name' => 'Μπάσα Νεπάλ'),
                array('code' => 'bsk', 'name' => 'Μπουρουσάσκι'),
                array('code' => 'bzd', 'name' => 'Μπρι-μπρι'),
                array('code' => 'moh', 'name' => 'Μώχωκ'),
                array('code' => 'nv', 'name' => 'Ναβαχικά'),
                array('code' => 'nah', 'name' => 'Ναουάτλ'),
                array('code' => 'na', 'name' => 'Ναουρουϊκά'),
                array('code' => 'nap', 'name' => 'Ναπολιτανικά'),
                array('code' => 'nsk', 'name' => 'Νασκαπικά'),
                array('code' => 'ng', 'name' => 'Νδονγικά'),
                array('code' => 'ne', 'name' => 'Νεπαλικά'),
                array('code' => 'nog', 'name' => 'Νογκάι'),
                array('code' => 'no', 'name' => 'Νορβηγικά Bokmål'),
                array('code' => 'nn', 'name' => 'Νορβηγικά Nynorsk'),
                array('code' => 'nr', 'name' => 'Νοτιο-νδεβελικά'),
                array('code' => 'ii', 'name' => 'Νουόσου'),
                array('code' => 'prs', 'name' => 'Ντάρι'),
                array('code' => 'dz', 'name' => 'Ντζόνγκα'),
                array('code' => 'dv', 'name' => 'Ντιβέχι'),
                array('code' => 'din', 'name' => 'Ντίνκα'),
                array('code' => 'ota', 'name' => 'Οθωμανικά τουρκικά'),
                array('code' => 'ryu', 'name' => 'Οκινάουα'),
                array('code' => 'nl', 'name' => 'Ολλανδικά'),
                array('code' => 'oc', 'name' => 'Οξιτανικά'),
                array('code' => 'osa', 'name' => 'Οσάγκε'),
                array('code' => 'os', 'name' => 'Οσσετικά'),
                array('code' => 'cy', 'name' => 'Ουαλικά'),
                array('code' => 'hu', 'name' => 'Ουγγρικά'),
                array('code' => 'udm', 'name' => 'Ουδμουρτικά'),
                array('code' => 'uz', 'name' => 'Ουζμπεκικά'),
                array('code' => 'ug', 'name' => 'Ουιγουρικά'),
                array('code' => 'uk', 'name' => 'Ουκρανικά'),
                array('code' => 'wo', 'name' => 'Ουολοφικά'),
                array('code' => 'ur', 'name' => 'Ουρντού'),
                array('code' => 'pau', 'name' => 'Παλαυανικά'),
                array('code' => 'pln', 'name' => 'Παλενκικά'),
                array('code' => 'pi', 'name' => 'Παλικά'),
                array('code' => 'pag', 'name' => 'Πανγκασικά'),
                array('code' => 'pap', 'name' => 'Παπιαμέντο'),
                array('code' => 'ps', 'name' => 'Παστουνικά'),
                array('code' => 'pms', 'name' => 'Πεδεμοντικά'),
                array('code' => 'fa', 'name' => 'Περσικά'),
                array('code' => 'pcd', 'name' => 'Πικαρδικά'),
                array('code' => 'pl', 'name' => 'Πολωνικά'),
                array('code' => 'pt', 'name' => 'Πορτογαλικά'),
                array('code' => 'fuc', 'name' => 'Πούλαρ'),
                array('code' => 'rap', 'name' => 'Ραπα-Νούι'),
                array('code' => 'rhg', 'name' => 'Ροϊγκιακά'),
                array('code' => 'rom', 'name' => 'Ρόμα'),
                array('code' => 'cgg', 'name' => 'Ρουκίγκα'),
                array('code' => 'ro', 'name' => 'Ρουμάνικα'),
                array('code' => 'rue', 'name' => 'Ρούσιν'),
                array('code' => 'ru', 'name' => 'Ρώσσικα'),
                array('code' => 'sm', 'name' => 'Σαμοαϊκά'),
                array('code' => 'sg', 'name' => 'Σανγικά'),
                array('code' => 'sa', 'name' => 'Σανσκριτικά'),
                array('code' => 'sc', 'name' => 'Σαρδηνικά'),
                array('code' => 'ceb', 'name' => 'Σεμπουάνο'),
                array('code' => 'sr', 'name' => 'Σερβικά'),
                array('code' => 'srr', 'name' => 'Σερέρ'),
                array('code' => 'trv', 'name' => 'Σηδικά'),
                array('code' => 'scn', 'name' => 'Σικελικά'),
                array('code' => 'si', 'name' => 'Σιναλικά'),
                array('code' => 'sd', 'name' => 'Σινδικά'),
                array('code' => 'sco', 'name' => 'Σκωττικά'),
                array('code' => 'mk', 'name' => 'Σλαβομακεδονικά'),
                array('code' => 'sk', 'name' => 'Σλοβακικά'),
                array('code' => 'sl', 'name' => 'Σλοβενικά'),
                array('code' => 'so', 'name' => 'Σομαλικά'),
                array('code' => 'sn', 'name' => 'Σονικά'),
                array('code' => 'st', 'name' => 'Σότο'),
                array('code' => 'sw', 'name' => 'Σουαχίλι'),
                array('code' => 'swg', 'name' => 'Σουηβικά Γερμανικά'),
                array('code' => 'sv', 'name' => 'Σουηδικά'),
                array('code' => 'su', 'name' => 'Σουνδανικά'),
                array('code' => 'syl', 'name' => 'Συλετικά'),
                array('code' => 'ss', 'name' => 'Σωατικά'),
                array('code' => 'tl', 'name' => 'Ταγκαλόγκ'),
                array('code' => 'th', 'name' => 'Ταϊλανδικά'),
                array('code' => 'ty', 'name' => 'Ταϊτιανά'),
                array('code' => 'tzm', 'name' => 'Ταμαζική Κεντρικού Άτλαντος'),
                array('code' => 'ta', 'name' => 'Ταμίλ'),
                array('code' => 'tmh', 'name' => 'Ταργική'),
                array('code' => 'tt', 'name' => 'Ταταρικά'),
                array('code' => 'crh', 'name' => 'Ταταρικά Κριμαίας'),
                array('code' => 'tg', 'name' => 'Τατζικικά'),
                array('code' => 'te', 'name' => 'Τελούγκου'),
                array('code' => 'tet', 'name' => 'Τέτουμ'),
                array('code' => 'ti', 'name' => 'Τιγρινικά'),
                array('code' => 'tli', 'name' => 'Τλινγκιτ'),
                array('code' => 'jam', 'name' => 'Τξαμαικανά Πατουά'),
                array('code' => 'to', 'name' => 'Τογκικά'),
                array('code' => 'tpi', 'name' => 'Τοκ Πισίν'),
                array('code' => 'x', 'name' => 'Τόκι Πόνα'),
                array('code' => 'srn', 'name' => 'Τονγκο-Σρανανικά'),
                array('code' => 'tdn', 'name' => 'Τοντάνο'),
                array('code' => 'tw', 'name' => 'Τούι'),
                array('code' => 'tr', 'name' => 'Τουρκικά'),
                array('code' => 'tk', 'name' => 'Τουρκμενικά'),
                array('code' => 'tus', 'name' => 'Τουσκαρόρα'),
                array('code' => 'tn', 'name' => 'Τσβάνα'),
                array('code' => 'chr', 'name' => 'Τσεροκικά'),
                array('code' => 'ce', 'name' => 'Τσετσένικα'),
                array('code' => 'cs', 'name' => 'Τσεχικά'),
                array('code' => 'ny', 'name' => 'Τσιτσεβαχικά'),
                array('code' => 'ts', 'name' => 'Τσονγκικά'),
                array('code' => 'cv', 'name' => 'Τσουβασικά'),
                array('code' => 'yua', 'name' => 'Υουκατικά Μάγια'),
                array('code' => 'fi', 'name' => 'Φινλανδικά'),
                array('code' => 'vls', 'name' => 'Φλαμανδικά'),
                array('code' => 'ff', 'name' => 'Φουλαϊκά'),
                array('code' => 'fur', 'name' => 'Φριουλικά'),
                array('code' => 'haw', 'name' => 'Χαβαϊκά'),
                array('code' => 'hak', 'name' => 'Χάκκα'),
                array('code' => 'ch', 'name' => 'Χαμορρικά'),
                array('code' => 'kca', 'name' => 'Χαντικά'),
                array('code' => 'ha', 'name' => 'Χάουσα'),
                array('code' => 'hz', 'name' => 'Χερερικά'),
                array('code' => 'ho', 'name' => 'Χίρι μότου'),
                array('code' => 'km', 'name' => 'Χμερικά'),
                array('code' => 'hmn', 'name' => 'Χμονγκ'),
                array('code' => 'xh', 'name' => 'Χόζα'),
            )
        );

        \DB::table('language_levels')->insert(
            array(
                array('description'   => 'Επιλέξτε επίπεδο'),
                array('description'   => 'Χαμηλό'),
                array('description'   => 'Μέτριο'),
                array('description'   => 'Καλό'),
                array('description'   => 'Πολύ Καλό'),
                array('description'   => 'Άριστο'),
            )
        );
    }
}
